[tool.poetry]
name = "internal-scripts"
version = "0.1.0"
description = ""
authors = ["Anton Shcherbak <shcherbak.a@work.ru>"]

[tool.poetry.dependencies]
python = "3.11"
dynaconf = "^3.1.11"
SQLAlchemy-Utils = "^0.38.3"
pydantic = "^1.10.2"
psycopg2 = "^2.9.5"
cryptography = "^38.0.4"
pre-commit = "^2.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"